#!/usr/bin/env python
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from vsc_irods.session import VSCiRODSSession


desc = """irm-like command using the VSC Python iRODS client

Example:

vsc-prc-irm -r "~/data/molec*" "~/data/README" --interactive --verbose
"""

arg_parser = ArgumentParser(description=desc,
                            formatter_class=RawDescriptionHelpFormatter)

arg_parser.add_argument('args', nargs='*',
                        help='glob pattern(s) for iRODS collections and data '
                        'objects to be removed. '
                        'Note that, when including asterisks or a tilde in '
                        'in a pattern, the pattern needs to be enclosed in '
                        'quotes to avoid shell expansion to local paths.')

arg_parser.add_argument('-i', '--interactive', action='store_true',
                        help='Switch to an "interactive" mode where you will '
                        'be asked for confirmation before any removal')

arg_parser.add_argument('-r', '--recurse', action='store_true',
                        help='Turns on recursion')

arg_parser.add_argument('-f', '--force', action='store_true',
                        help='Complete removal, instead of sending to trash')

arg_parser.add_argument('-v', '--verbose', action='store_true',
                        help='Increases the verbosity level')

options = arg_parser.parse_args()


with VSCiRODSSession(txt='-') as session:
    for arg in options.args:
        session.bulk.remove(arg, prompt=options.interactive,
                            recurse=options.recurse,
                            force=options.force,
                            verbose=options.verbose)
