#!/usr/bin/env python
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from vsc_irods.session import VSCiRODSSession


desc = """imv-like command using the VSC Python iRODS client for moving
or renaming collections and data objects.

Example:

vsc-prc-imv "tmpfiles*" "~/tmpdir"  --verbose
vsc-prc-imv ./parent/dirname ./parent/filename destination
"""

arg_parser = ArgumentParser(description=desc,
                            formatter_class=RawDescriptionHelpFormatter)

arg_parser.add_argument('args', nargs='*',
                        help='glob pattern(s) for iRODS collections and data '
                        'objects to be moved. '
                        'Note that, when including asterisks or a tilde in '
                        'in a pattern, the pattern needs to be enclosed in '
                        'quotes to avoid shell expansion to local paths.')

arg_parser.add_argument('dest',
                        help='Destination where the iRODS collections and data '
                        'objects will be moved to. '
                        'Note that, when including asterisks or a tilde in '
                        'in a pattern, the pattern needs to be enclosed in '
                        'quotes to avoid shell expansion to local paths.')

arg_parser.add_argument('-i', '--interactive', action='store_true',
                        help='Switch to an "interactive" mode where you will '
                        'be asked for confirmation before each move')

arg_parser.add_argument('-v', '--verbose', action='store_true',
                        help='Increases the verbosity level')

options = arg_parser.parse_args()


with VSCiRODSSession(txt='-') as session:
    for arg in options.args:
        session.bulk.move(arg, options.dest,
                          prompt=options.interactive,
                          verbose=options.verbose)
