#!/usr/bin/env python
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from vsc_irods.session import VSCiRODSSession


desc = """Add job-related metadata to selected data objects and collections

Can only be used as part of a job sent to a PBS- or SLURM-based scheduler

Examples:

vsc-prc-add-job-metadata "~/data/*.out"
"""

arg_parser = ArgumentParser(description=desc,
                            formatter_class=RawDescriptionHelpFormatter)

arg_parser.add_argument('args', nargs='*',
                        help='glob pattern(s) for iRODS collections and data '
                        'objects to which job-related metadata will be added. '
                        'Note that, when including asterisks or a tilde in '
                        'in a pattern, the pattern needs to be enclosed in '
                        'quotes to avoid shell expansion to local paths.')

arg_parser.add_argument('-r', '--recurse', action='store_true',
                        help='Turns on recursion.')

arg_parser.add_argument('-v', '--verbose', action='store_true',
                        help='Increases the verbosity level.')

options = arg_parser.parse_args()


with VSCiRODSSession(txt='-') as session:
    for arg in options.args:
        session.bulk.add_job_metadata(arg, recurse=options.recurse,
                                      verbose=options.verbose)
